### PR TITLE
Add basic Daijirin support

### PR DESCRIPTION
**Pull request by mertvn**

### CODE REVIEW

**Comment by wareya** [comment]
Wow! Thank you so much. I'll review this when I have the free time (next day or two -- three at the worst).

**Comment by wareya** [comment]
A couple (very small) things:

1) J-J, J-E, and E-J should probably all be separate output configurations. The smaller the dictionary, the better of a time nazeka has, and if someone really wants J-E, they probably shouldn't have to load J-J at the same time. I also expect E-J to be used very infrequently.
2) Coming off of 1, the words for the different language pairings should probably be written in full English, because someone who wants the J-E dictionary might not know what waei and eiwa mean.

Aside from those two notes, I have no objections.

I can merge first and make these changes myself if you want, but if you want to do it yourself, feel free. (If you don't respond for a few days I'll just merge and do it myself).

**Comment by mertvn** [comment]
I'd prefer if you made those changes yourself. Thanks!

**Comment by wareya** [comment]
Cheers!

**Pull request merged**
